### PR TITLE
Fix validation of Callable in a compound trait

### LINKED ISSUE #793: Unexpected validation failure when using Callable with Either
The tests fail when I expected them to pass:
```
from functools import partial

import unittest

from traits.api import Callable, Either, HasRequiredTraits


def dummy(x):
    pass


class Foo(HasRequiredTraits):

    function = Callable()

    function_or_none = Either(None, Callable())


class TestCallable(unittest.TestCase):

    def test_none(self):
        foo = Foo()
        foo.function = None
        foo.function_or_none = None

    def test_partial_function(self):
        foo = Foo()
        foo.function = partial(dummy)
        foo.function_or_none = partial(dummy)


if __name__ == "__main__":
    unittest.main()
```

with results:
```
======================================================================
ERROR: test_none (__main__.TestCallable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "callable_example.py", line 24, in test_none
    foo.function_or_none = None
  File "/Users/kchoi/ETS/traits/traits/base_trait_handler.py", line 77, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The 'function_or_none' trait of a Foo instance must be a callable value or None, but a value of None <class 'NoneType'> was specified.

======================================================================
ERROR: test_partial_function (__main__.TestCallable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "callable_example.py", line 29, in test_partial_function
    foo.function_or_none = partial(dummy)
  File "/Users/kchoi/ETS/traits/traits/base_trait_handler.py", line 77, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: The 'function_or_none' trait of a Foo instance must be a callable value or None, but a value of functools.partial(<function dummy at 0x10805a8c8>) <class 'functools.partial'> was specified.
```

### PR DESCRIPTION
**Pull request by mdickinson**
Fix validation of a `Callable` trait inside an `Either`.

Fixes #793

### CODE REVIEW

File: traits/ctraits.c [hunk 1]
```diff
@@ -4223,7 +4229,7 @@ static int
 _set_trait_comparison_mode(trait_object *trait, PyObject *value, void *closure)
 {
     long comparison_mode = PyLong_AsLong(value);
-    
+
```
Comment (mdickinson) [inline traits/ctraits.c]: VS Code did this, not me! (Apparently there was some trailing whitespace in ctraits.c)

**Comment by kitchoi** [comment]
Yes I can review.  Thank you for fixing it!
