### PR TITLE
Remove HasTraits.trait_monitor

### LINKED ISSUE #569: Consider removing the HasTraits.trait_monitor method
There's a little-used method on `HasTraits` called `trait_monitor`, that allows arbitrary callbacks to be called on instantiation of a particular `HasTraits` subclass:

```
>>> from traits.api import *
>>> class A(HasTraits):
...     foo = Int
... 
>>> def handler(*args, **kwargs):
...     print("handler called")
...     print("args: ", args)
...     print("kwargs: ", kwargs)
... 
>>> A.trait_monitor(handler)
>>> a = A()
handler called
args:  (<__main__.A object at 0x7ff6d825cd00>,)
kwargs:  {}
```

However:

- this method is unused elsewhere, as far as I'm able to tell
- it's neither documented nor tested
- it's implemented via a piece of global state that keeps track of all current monitors
- it's currently broken: an attempt to use `remove=True` fails with a `ValueError`:

```
>>> A.trait_monitor(handler, remove=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mdickinson/.edm/envs/tt/lib/python3.6/site-packages/traits/has_traits.py", line 1198, in trait_monitor
    index = _trait_monitor_index(cls, handler)
  File "/Users/mdickinson/.edm/envs/tt/lib/python3.6/site-packages/traits/has_traits.py", line 893, in _trait_monitor_index
    for i, _cls, _handler in enumerate(_HasTraits_monitors):
ValueError: not enough values to unpack (expected 3, got 2)
```

Given all that, and given that we have limited resources and many more useful things to focus on, I'd suggest that we remove this method and the associated machinery.

### PR DESCRIPTION
**Pull request by mdickinson**
This PR removes the `HasTraits.trait_monitor` method: the current implementation is broken, undocumented, untested, and (as far as I can tell) unused elsewhere. As such, it's not worth the maintenance burden.

Closes #569

### CODE REVIEW

File: traits/ctraits.c [hunk 1]
```diff
@@ -942,24 +941,6 @@ has_traits_init ( PyObject * obj, PyObject * args, PyObject * kwds ) {
         Py_DECREF( value );
     }
 
-    /* Notify any interested monitors that a new object has been created: */
-    for ( i = 0, n = PyList_GET_SIZE( _HasTraits_monitors ); i < n; i++ ) {
-        value = PyList_GET_ITEM( _HasTraits_monitors, i );
```
Comment (mdickinson) [inline traits/ctraits.c]: Note that apart from the obvious issue that a second call to `trait_monitor` always fails, there's a more subtle problem in this C code: the use of `GET_ITEM` here is unsafe, and given that we're calling arbitrary Python code on each iteration (the handler could be doing anything), it's not safe to assume that the list hasn't changed size while we're iterating over it.

File: traits/ctraits.c [hunk 2]
```diff
@@ -942,24 +941,6 @@ has_traits_init ( PyObject * obj, PyObject * args, PyObject * kwds ) {
...
-        assert( PyTuple_GET_SIZE( value ) == 2 );
-
-        klass   = PyTuple_GET_ITEM( value, 0 );
-        handler = PyTuple_GET_ITEM( value, 1 );
-
-        if ( PyObject_IsInstance( obj, klass ) > 0 ) {
-            handler_args = PyTuple_New( 1 );
-            PyTuple_SetItem( handler_args, 0, obj );
-            Py_INCREF( obj );
-            PyObject_Call( handler, handler_args, NULL );
```
Comment (mdickinson) [inline traits/ctraits.c]: This is also unsafe: we're calling arbitrary code that could raise an exception, and not checking the return value.

File: traits/ctraits.c [hunk 3]
```diff
@@ -5353,16 +5334,6 @@ Py2to3_MOD_INIT(ctraits) {
                          (PyObject *) &trait_type ) < 0 )
        return Py2to3_MOD_ERROR_VAL;
 
-    /* Create the 'HasTraitsMonitor' list: */
-    tmp = PyList_New( 0 );
-    Py_INCREF( tmp );
```
Comment (mdickinson) [inline traits/ctraits.c]: It looks as though `tmp` is now unused. Needs fixing.

Comment (mdickinson) [reply traits/ctraits.c]: Fixed, along with various other unused variables. I've double checked that there are no more warnings from the compiler output.

**Comment by mdickinson** [comment]
Travis build has completed, but the notification doesn't seem to have arrived.

File: traits/ctraits.c [hunk 4]
```diff
@@ -901,10 +900,6 @@ has_traits_init ( PyObject * obj, PyObject * args, PyObject * kwds ) {
 
     PyObject * key;
     PyObject * value;
-    PyObject * klass;
-    PyObject * handler;
-    PyObject * handler_args;
-    int n;
     int has_listeners;
     Py_ssize_t i = 0;
```
Comment (rahulporuri) [inline traits/ctraits.c]: It looks like `i` isn't used anywhere in `has_traits_init` (now that the trait monitor code is out).

Comment (rahulporuri) [reply traits/ctraits.c]: never mind. im wrong. it is being used when setting traits.
