### PR TITLE
Handle missing TraitError _better_

### LINKED ISSUE #671: Awkward behavior when instantiating cTrait
```
>>> from traits.ctraits import cTrait
>>> cTrait(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'traits.ctraits.cTrait'> returned NULL without setting an error
>>> cTrait(11)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <class 'traits.ctraits.cTrait'> returned NULL without setting an error
>>> cTrait(1)
<traits.ctraits.cTrait object at 0x102615f48>
```

Note that adding a `import traits.traits` forces the expected behavior - 

```
>>> import traits.traits
>>> cTrait(11)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
traits.trait_errors.TraitError: Invalid argument to trait constructor.
```

### PR DESCRIPTION
**Pull request by corranwebster**
Import Undefined, Uninitialized, TraitError and DelegateError in ctraits.c

This removes code which injects these objects into ctraits.c dynamically during import of trait_base and trait_errors.

Fixes #671

### CODE REVIEW

File: traits/ctraits.c [hunk 1]
```diff
@@ -5045,5 +5009,35 @@ PyMODINIT_FUNC PyInit_ctraits(void) {
...
     is_callable = PyLong_FromLong( -1 );
 
+    /* Import Undefined and Uninitialized */
+    trait_base = PyImport_ImportModule("traits.trait_base");
+    if (trait_base == NULL) {
+        return NULL;
+    }
+    Undefined = PyObject_GetAttrString(trait_base, "Undefined");
+    if (Undefined == NULL) {
+        return NULL;
```
Comment (mdickinson) [inline traits/ctraits.c]: This branch needs a `Py_DECREF(trait_base)`

**Comment by mdickinson** [comment]
> I might make a separate PR to handle module finalization

Related: #694

**Comment by mdickinson** [comment]
Assigning to me for minor updates and merge.

**Comment by mdickinson** [comment]
Merging if/when CI agrees.
