### PR TITLE
Fix exception-swallowing behaviour of tuple validation

### LINKED ISSUE #1389: Tuple validation turns all exceptions into TraitError
Currently, validation of a `Tuple` trait type turns all exceptions into `TraitError`. In general, this is undesirable behaviour, since it risks masking genuine programming errors. It should instead propagate exceptions other than `TraitError`.

Nevertheless, changing this would be a backwards incompatible change. We may want to warn (with a `DeprecationWarning`) on exceptions other than `TraitError`, and only propagate those exceptions in Traits 7.0.

### PR DESCRIPTION
**Pull request by mdickinson**
This PR fixes tuple validation so that exceptions that occur when validating tuple subitems are propagated, instead of swallowed and ultimately turned into `TraitError`s.

Fixes #1389.

**Checklist**
- [x] Tests
- [ ] Update API reference (`docs/source/traits_api_reference`)  N/A
- [ ] Update User manual (`docs/source/traits_user_manual`)  N/A
- [ ] Update type annotation hints in `traits-stubs`  N/A

### CODE REVIEW

File: traits/ctraits.c [hunk 1]
```diff
@@ -3484,6 +3484,16 @@ validate_trait_prefix_map(
...
 +----------------------------------------------------------------------------*/
 
+/* Note: this function does not follow standard CPython error-handling rules.
+   There are three possible types of outcome for this function.
+
+   If validation fails, NULL is returned and no Python exception is set
+     (contrary to usual Python C-API conventions).
+   If an unexpected exception occurs, NULL is returned and a Python exception
+     is set.
+   If validation succeeds, the validated object is returne.
```
Comment (mdickinson) [inline traits/ctraits.c:3494]:
```suggestion
   If validation succeeds, the validated object is returned.
```

File: traits/ctraits.c [hunk 2]
```diff
@@ -3908,7 +3919,7 @@ validate_trait_complex(
             case 9: /* Tuple item check: */
                 result = validate_trait_tuple_check(
                     PyTuple_GET_ITEM(type_info, 1), obj, name, value);
-                if (result != NULL) {
+                if (result != NULL || PyErr_Occurred()) {
```
Comment (mdickinson) [inline traits/ctraits.c:3922]: The `||` path here is not currently exercised by the regression test. Fixing ...

Comment (mdickinson) [reply traits/ctraits.c:3922]: Fixed.

File: traits/ctraits.c [hunk 3]
```diff
@@ -3505,12 +3515,13 @@ validate_trait_tuple_check(
                 }
                 else {
                     aitem = itrait->validate(itrait, obj, name, bitem);
-                }
-
-                if (aitem == NULL) {
-                    PyErr_Clear();
-                    Py_XDECREF(tuple);
-                    return NULL;
+                    if (aitem == NULL) {
```
Comment (mdickinson) [inline traits/ctraits.c:3518]: Note to reviewers: this exception-handling block was moved inside the `else`; this doesn't change behaviour (since there's no way that the `if` branch can result in `aitem` being `NULL`), but it improves the readability of the code a smidgen by bringing the exception handling closer to the `itrait->validate` call that the exception is being handled for.

Comment (mdickinson) [reply traits/ctraits.c]: For the sake of clarity, I've reverted the refactor.

**Review by kitchoi — APPROVED** [review]
LGTM
