### PR TITLE
Refactor: fix duplication of DEFAULT_VALUE constants

### LINKED ISSUE #686: Proposal : Expose int constants in the traits.ctraits module
At the moment, we are defining a few constants in two places - e.g. `TRAIT_DICT_OBJECT_DEFAULT_VALUE` is defined in in `traits.ctraits` and in `traits.trait_handlers`.

Instead, we can use `PyModule_AddIntConstant` or `PyModuleAddIntMacro` to expose the variables defined in the `traits.ctraits` module - which can then be imported by others.

Ref : https://docs.python.org/3.6/c-api/module.html#support-functions

Note : There are a few constants that need to be defined (and used) in `traits.ctraits` e.g. trait kind value and the various type checks

### PR DESCRIPTION
**Pull request by mdickinson**
This is a recreation of #688. This PR re-uses the *_DEFAULT_VALUE constants defined in `ctraits.c` in `constants.py`, instead  of duplicating the integer values.

This is pure refactor, so there should be no change in behaviour (and consequently, no new tests or documentation needed).

Closes #686.

### CODE REVIEW

File: traits/ctraits.c [hunk 1]
```diff
@@ -5572,5 +5573,96 @@ PyInit_ctraits(void)
...
+        return NULL;
+    }
+    error = PyModule_AddIntConstant(
+        module,
+        "_CALLABLE_AND_ARGS_DEFAULT_VALUE",
+        CALLABLE_AND_ARGS_DEFAULT_VALUE
+    );
+    if (error < 0) {
+        return NULL;
+    }
```
Comment (kitchoi) [inline traits/ctraits.c]: [OCD] I noticed that the ordering of the above three constants match the ordering in `DefaultValue` but not in the ordering in `ctraits.c`. :( [/OCD]

Comment (mdickinson) [reply traits/ctraits.c]: Yes, that was deliberate: it  seemed to make sense to keep the set/list/dict variants together.

**Comment by mdickinson** [comment]
Random job failure on Travis (while installing MKL); I've restarted the relevant job.
